services:
  print_server:
    container_name: print_server
    build: .
    env_file: web/.env
    environment:
      - BACKEND
      - PRINTER
      - MEDIA
      - FONT
      - MOTOR_INITIAL
      - MOTOR_FINAL
    ports:
      - "80:80"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb # USB Printer
    volumes:
      - /sys/class/pwm:/sys/class/pwm
    restart: always
