[project]
name = "servo_motor_control"
version = "1.0"
description = "Simple ServoMotor Control for OrangePi to press BrotherLabelPrinter Power Button"
readme = "README.md"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
