[project]
name = "servo_motor_control"
version = "1.0"
description = "Simple ServoMotor Control for OrangePi to press BrotherLabelPrinter Power Button"
readme = "README.md"
requires-python = ">=3.13"

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
